#!/usr/bin/env python
# Direct entry executable

import os, sys

_srcdir = 'source'

if getattr(sys, 'frozen', False):
    # The application is frozen
    _filepath = os.path.dirname(os.path.realpath(sys.executable))
else:
    # The application is not frozen
    # Change this bit to match where you store your data files:
    _filepath = os.path.dirname(os.path.realpath(__file__))

# Make sure the right source is imported
sys.path.insert(1, os.path.join(_filepath, _srcdir))

if __name__ == '__main__':
    if sys.version_info[0] == 3:
        # Main entry point
        from you_get import main
        main(repo_path=_filepath)
    else:
        from you_get.utils.log import *
        wtf("Python 3 is required.",
            "If Python 3 is already installed, run this script using 'python3 you-get'.")
